apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jf7en4wfh-go 
  janus-idp.io/tekton: jf7en4wfh-go
  backstage.io/kubernetes-id: jf7en4wfh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jf7en4wfh-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  