apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jf7en4wfh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jf7en4wfh-go 
  name: jf7en4wfh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jf7en4wfh-go 
